theme: jekyll-theme-cayman
title: Stochastic Control and its Applications (A workshop dedicated to Sean Meyn’s 60 th birthday)
subtitle: 57th IEEE Conference on Decision and Control, Miami Beach, 2018
